services:
  ubuntu:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TAG=22.04
    image: plain:22.04
    hostname: ubuntu
    env_file:
      - ./devcontainer.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true